(* generated by dune *)

(** @canonical Expect_test_common.Expectation *)
module Expectation = Expect_test_common__Expectation

(** @canonical Expect_test_common.File *)
module File = Expect_test_common__File

(** @canonical Expect_test_common.Import *)
module Import = Expect_test_common__Import
