(* generated by dune *)

(** @canonical Iomux.Config *)
module Config = Iomux__Config

(** @canonical Iomux.Poll *)
module Poll = Iomux__Poll

(** @canonical Iomux.Util *)
module Util = Iomux__Util

module Iomux__ = struct end
[@@deprecated "this module is shadowed"]
