(* generated by dune *)

(** @canonical Eio_unix.Cap *)
module Cap = Eio_unix__Cap

(** @canonical Eio_unix.Fd *)
module Fd = Eio_unix__Fd

(** @canonical Eio_unix.Fork_action *)
module Fork_action = Eio_unix__Fork_action

(** @canonical Eio_unix.Inherit_fds *)
module Inherit_fds = Eio_unix__Inherit_fds

(** @canonical Eio_unix.Net *)
module Net = Eio_unix__Net

(** @canonical Eio_unix.Pi *)
module Pi = Eio_unix__Pi

(** @canonical Eio_unix.Private *)
module Private = Eio_unix__Private

(** @canonical Eio_unix.Process *)
module Process = Eio_unix__Process

(** @canonical Eio_unix.Rcfd *)
module Rcfd = Eio_unix__Rcfd

(** @canonical Eio_unix.Resource *)
module Resource = Eio_unix__Resource

(** @canonical Eio_unix.Thread_pool *)
module Thread_pool = Eio_unix__Thread_pool

(** @canonical Eio_unix.Types *)
module Types = Eio_unix__Types

module Eio_unix__ = struct end
[@@deprecated "this module is shadowed"]
