(* generated by dune *)

(** @canonical Mirage_crypto.Aead *)
module Aead = Mirage_crypto__Aead

(** @canonical Mirage_crypto.Ccm *)
module Ccm = Mirage_crypto__Ccm

(** @canonical Mirage_crypto.Chacha20 *)
module Chacha20 = Mirage_crypto__Chacha20

(** @canonical Mirage_crypto.Cipher_block *)
module Cipher_block = Mirage_crypto__Cipher_block

(** @canonical Mirage_crypto.Cipher_stream *)
module Cipher_stream = Mirage_crypto__Cipher_stream

(** @canonical Mirage_crypto.Hash *)
module Hash = Mirage_crypto__Hash

(** @canonical Mirage_crypto.Native *)
module Native = Mirage_crypto__Native

(** @canonical Mirage_crypto.Poly1305 *)
module Poly1305 = Mirage_crypto__Poly1305

(** @canonical Mirage_crypto.Uncommon *)
module Uncommon = Mirage_crypto__Uncommon
