(* generated by dune *)

(** @canonical Cohttp_eio.Body *)
module Body = Cohttp_eio__Body

(** @canonical Cohttp_eio.Client *)
module Client = Cohttp_eio__Client

(** @canonical Cohttp_eio.Client_intf *)
module Client_intf = Cohttp_eio__Client_intf

(** @canonical Cohttp_eio.Io *)
module Io = Cohttp_eio__Io

(** @canonical Cohttp_eio.Server *)
module Server = Cohttp_eio__Server

(** @canonical Cohttp_eio.Utils *)
module Utils = Cohttp_eio__Utils
