(* generated by dune *)

(** @canonical Domain_local_await.Thread_intf *)
module Thread_intf = Domain_local_await__Thread_intf

module Domain_local_await__ = struct end
[@@deprecated "this module is shadowed"]
