(* generated by dune *)

(** @canonical Tls.Ciphersuite *)
module Ciphersuite = Tls__Ciphersuite

(** @canonical Tls.Config *)
module Config = Tls__Config

(** @canonical Tls.Core *)
module Core = Tls__Core

(** @canonical Tls.Crypto *)
module Crypto = Tls__Crypto

(** @canonical Tls.Engine *)
module Engine = Tls__Engine

(** @canonical Tls.Explorator *)
module Explorator = Tls__Explorator

(** @canonical Tls.Handshake_client *)
module Handshake_client = Tls__Handshake_client

(** @canonical Tls.Handshake_client13 *)
module Handshake_client13 = Tls__Handshake_client13

(** @canonical Tls.Handshake_common *)
module Handshake_common = Tls__Handshake_common

(** @canonical Tls.Handshake_crypto *)
module Handshake_crypto = Tls__Handshake_crypto

(** @canonical Tls.Handshake_crypto13 *)
module Handshake_crypto13 = Tls__Handshake_crypto13

(** @canonical Tls.Handshake_server *)
module Handshake_server = Tls__Handshake_server

(** @canonical Tls.Handshake_server13 *)
module Handshake_server13 = Tls__Handshake_server13

(** @canonical Tls.Packet *)
module Packet = Tls__Packet

(** @canonical Tls.Reader *)
module Reader = Tls__Reader

(** @canonical Tls.State *)
module State = Tls__State

(** @canonical Tls.Utils *)
module Utils = Tls__Utils

(** @canonical Tls.Writer *)
module Writer = Tls__Writer
