(* generated by dune *)

(** @canonical Base_quickcheck.Bigarray_helpers *)
module Bigarray_helpers = Base_quickcheck__Bigarray_helpers

(** @canonical Base_quickcheck.Export *)
module Export = Base_quickcheck__Export

(** @canonical Base_quickcheck.Generator *)
module Generator = Base_quickcheck__Generator

(** @canonical Base_quickcheck.Observer *)
module Observer = Base_quickcheck__Observer

(** @canonical Base_quickcheck.Observer0 *)
module Observer0 = Base_quickcheck__Observer0

(** @canonical Base_quickcheck.Shrinker *)
module Shrinker = Base_quickcheck__Shrinker

(** @canonical Base_quickcheck.Test *)
module Test = Base_quickcheck__Test

(** @canonical Base_quickcheck.Test_intf *)
module Test_intf = Base_quickcheck__Test_intf

(** @canonical Base_quickcheck.With_basic_types *)
module With_basic_types = Base_quickcheck__With_basic_types
