(* generated by dune *)

(** @canonical Base_for_tests.Test_binary_searchable *)
module Test_binary_searchable = Base_for_tests__Test_binary_searchable

(** @canonical Base_for_tests.Test_binary_searchable_intf *)
module Test_binary_searchable_intf = Base_for_tests__Test_binary_searchable_intf

(** @canonical Base_for_tests.Test_blit *)
module Test_blit = Base_for_tests__Test_blit

(** @canonical Base_for_tests.Test_blit_intf *)
module Test_blit_intf = Base_for_tests__Test_blit_intf
