(* generated by dune *)

(** @canonical Typerep_lib.Make_typename *)
module Make_typename = Typerep_lib__Make_typename

(** @canonical Typerep_lib.Named_intf *)
module Named_intf = Typerep_lib__Named_intf

(** @canonical Typerep_lib.Std *)
module Std = Typerep_lib__Std

(** @canonical Typerep_lib.Std_internal *)
module Std_internal = Typerep_lib__Std_internal

(** @canonical Typerep_lib.Type_abstract *)
module Type_abstract = Typerep_lib__Type_abstract

(** @canonical Typerep_lib.Type_equal *)
module Type_equal = Typerep_lib__Type_equal

(** @canonical Typerep_lib.Type_generic *)
module Type_generic = Typerep_lib__Type_generic

(** @canonical Typerep_lib.Type_generic_intf *)
module Type_generic_intf = Typerep_lib__Type_generic_intf

(** @canonical Typerep_lib.Typename *)
module Typename = Typerep_lib__Typename

(** @canonical Typerep_lib.Typerep_obj *)
module Typerep_obj = Typerep_lib__Typerep_obj

(** @canonical Typerep_lib.Typerepable *)
module Typerepable = Typerep_lib__Typerepable

(** @canonical Typerep_lib.Variant_and_record_intf *)
module Variant_and_record_intf = Typerep_lib__Variant_and_record_intf
