(* generated by dune *)

(** @canonical Uring.Config *)
module Config = Uring__Config

(** @canonical Uring.Heap *)
module Heap = Uring__Heap

(** @canonical Uring.Region *)
module Region = Uring__Region
