language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: false
services:
  - docker
env:
  global:
    - DISTRO=alpine
    - TESTS=true
    - PACKAGE="duration"
  matrix:
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.04
notifications:
  email: false
