(* generated by dune *)

(** @canonical Eio_posix.Config *)
module Config = Eio_posix__Config

(** @canonical Eio_posix.Domain_mgr *)
module Domain_mgr = Eio_posix__Domain_mgr

(** @canonical Eio_posix.Err *)
module Err = Eio_posix__Err

(** @canonical Eio_posix.Flow *)
module Flow = Eio_posix__Flow

(** @canonical Eio_posix.Fs *)
module Fs = Eio_posix__Fs

(** @canonical Eio_posix.Low_level *)
module Low_level = Eio_posix__Low_level

(** @canonical Eio_posix.Net *)
module Net = Eio_posix__Net

(** @canonical Eio_posix.Path *)
module Path = Eio_posix__Path

(** @canonical Eio_posix.Process *)
module Process = Eio_posix__Process

(** @canonical Eio_posix.Sched *)
module Sched = Eio_posix__Sched

(** @canonical Eio_posix.Time *)
module Time = Eio_posix__Time

module Eio_posix__ = struct end
[@@deprecated "this module is shadowed"]
