(* generated by dune *)

(** @canonical Ppx_optcomp.Cparser *)
module Cparser = Ppx_optcomp__Cparser

(** @canonical Ppx_optcomp.Interpreter *)
module Interpreter = Ppx_optcomp__Interpreter

(** @canonical Ppx_optcomp.Token *)
module Token = Ppx_optcomp__Token
