(* generated by dune *)

(** @canonical Yojson.Basic *)
module Basic = Yojson__Basic

(** @canonical Yojson.Codec *)
module Codec = Yojson__Codec

(** @canonical Yojson.Common *)
module Common = Yojson__Common

(** @canonical Yojson.Lexer_utils *)
module Lexer_utils = Yojson__Lexer_utils

(** @canonical Yojson.Raw *)
module Raw = Yojson__Raw

(** @canonical Yojson.Safe *)
module Safe = Yojson__Safe

(** @canonical Yojson.T *)
module T = Yojson__T
