.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "DUNE-FORMAT-DUNE-FILE" 1 "" "Dune 3.15.0" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'format\N'45'dune\N'45'file \N'45' Format dune files\N'46'
.SH SYNOPSIS
.P
\fBdune format\N'45'dune\N'45'file\fR [\fB\N'45'\N'45'dune\N'45'version\fR=\fIVERSION\fR] [\fIOPTION\fR]… [\fIFILE\fR]
.SH DESCRIPTION
.P
\fBdune format\N'45'dune\N'45'file\fR reads a dune file and outputs a formatted version\N'46' This is a low\N'45'level command, meant to implement editor support for example\N'46' To reformat a dune project, see the "Automatic formatting" section in the manual\N'46'
.SH ARGUMENTS
.TP 4
\fIFILE\fR
Path to the dune file to parse\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'dune\N'45'version\fR=\fIVERSION\fR (absent=\fB3\N'46'15\fR)
Which version of Dune language to use\N'46'
.SH COMMON OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH EXIT STATUS
.P
\fBdune format\N'45'dune\N'45'file\fR exits with:
.TP 4
0
on success\N'46'
.TP 4
1
if an error happened\N'46'
.TP 4
130
if it was interrupted by a signal\N'46'
.SH SEE ALSO
.P
dune(1)