.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "DUNE-RPC" 1 "" "Dune 3.15.0" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'rpc \N'45' Dune\N'39's RPC mechanism\N'46' Experimental\N'46'
.SH SYNOPSIS
.P
\fBdune rpc\fR \fICOMMAND\fR …
.SH DESCRIPTION
.P
This is experimental\N'46' do not use
.SH COMMANDS
.TP 4
\fBbuild\fR [\fIOPTION\fR]… [\fITARGET\fR]…
build a given target (requires dune to be running in passive watching mode)
.TP 4
\fBping\fR [\fIOPTION\fR]…
Ping the build server running in the current directory
.TP 4
\fBstatus\fR [\fIOPTION\fR]…
show active connections
.SH COMMON OPTIONS
.P
These options are common to all commands\N'46'
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH MORE HELP
.P
Use `\fBdune\fR \fICOMMAND\fR \N'45'\N'45'help\N'39' for help on a single command\N'46'
.SH EXIT STATUS
.P
\fBdune rpc\fR exits with:
.TP 4
0
on success\N'46'
.TP 4
1
if an error happened\N'46'
.TP 4
130
if it was interrupted by a signal\N'46'
.SH BUGS
.P
Check bug reports at https://github\N'46'com/ocaml/dune/issues
.SH SEE ALSO
.P
dune(1)