(* generated by dune *)

(** @canonical Optint.Int63_emul *)
module Int63_emul = Optint__Int63_emul

(** @canonical Optint.Int63_native *)
module Int63_native = Optint__Int63_native

(** @canonical Optint.Integer_interface *)
module Integer_interface = Optint__Integer_interface

(** @canonical Optint.Optint_emul *)
module Optint_emul = Optint__Optint_emul

(** @canonical Optint.Optint_native *)
module Optint_native = Optint__Optint_native
