(* generated by dune *)

(** @canonical Re2.Explicit_dependencies_unignored *)
module Explicit_dependencies_unignored = Re2__Explicit_dependencies_unignored

(** @canonical Re2.Options *)
module Options = Re2__Options

(** @canonical Re2.Parser *)
module Parser = Re2__Parser

(** @canonical Re2.Parser_intf *)
module Parser_intf = Re2__Parser_intf

(** @canonical Re2.Regex *)
module Regex = Re2__Regex

(** @canonical Re2.Regex_intf *)
module Regex_intf = Re2__Regex_intf
