opam-version: "2.0"
lib: [
  "_build/install/default/lib/dune/META"
  "_build/install/default/lib/dune/dune-package"
  "_build/install/default/lib/dune/opam"
]
bin: "_build/install/default/bin/dune"
share_root: [
  "_build/install/default/share/emacs/site-lisp/dune-flymake.el"
    {"emacs/site-lisp/dune-flymake.el"}
  "_build/install/default/share/emacs/site-lisp/dune-watch.el"
    {"emacs/site-lisp/dune-watch.el"}
  "_build/install/default/share/emacs/site-lisp/dune.el"
    {"emacs/site-lisp/dune.el"}
]
doc: [
  "_build/install/default/doc/dune/CHANGES.md"
  "_build/install/default/doc/dune/LICENSE.md"
  "_build/install/default/doc/dune/README.md"
  "_build/install/default/doc/dune/odoc-pages/index.mld"
    {"odoc-pages/index.mld"}
]
man: [
  "_build/install/default/man/man1/dune-build.1"
  "_build/install/default/man/man1/dune-cache.1"
  "_build/install/default/man/man1/dune-clean.1"
  "_build/install/default/man/man1/dune-coq.1"
  "_build/install/default/man/man1/dune-describe.1"
  "_build/install/default/man/man1/dune-diagnostics.1"
  "_build/install/default/man/man1/dune-exec.1"
  "_build/install/default/man/man1/dune-external-lib-deps.1"
  "_build/install/default/man/man1/dune-fmt.1"
  "_build/install/default/man/man1/dune-format-dune-file.1"
  "_build/install/default/man/man1/dune-help.1"
  "_build/install/default/man/man1/dune-init.1"
  "_build/install/default/man/man1/dune-install.1"
  "_build/install/default/man/man1/dune-installed-libraries.1"
  "_build/install/default/man/man1/dune-internal.1"
  "_build/install/default/man/man1/dune-monitor.1"
  "_build/install/default/man/man1/dune-ocaml-merlin.1"
  "_build/install/default/man/man1/dune-ocaml.1"
  "_build/install/default/man/man1/dune-pkg.1"
  "_build/install/default/man/man1/dune-printenv.1"
  "_build/install/default/man/man1/dune-promote.1"
  "_build/install/default/man/man1/dune-promotion.1"
  "_build/install/default/man/man1/dune-rpc.1"
  "_build/install/default/man/man1/dune-rules.1"
  "_build/install/default/man/man1/dune-runtest.1"
  "_build/install/default/man/man1/dune-show.1"
  "_build/install/default/man/man1/dune-shutdown.1"
  "_build/install/default/man/man1/dune-subst.1"
  "_build/install/default/man/man1/dune-test.1"
  "_build/install/default/man/man1/dune-top.1"
  "_build/install/default/man/man1/dune-uninstall.1"
  "_build/install/default/man/man1/dune-upgrade.1"
  "_build/install/default/man/man1/dune-utop.1"
  "_build/install/default/man/man1/dune.1"
  "_build/install/default/man/man5/dune-config.5"
]
