(* generated by dune *)

(** @canonical Cohttp.Accept *)
module Accept = Cohttp__Accept

(** @canonical Cohttp.Accept_lexer *)
module Accept_lexer = Cohttp__Accept_lexer

(** @canonical Cohttp.Accept_parser *)
module Accept_parser = Cohttp__Accept_parser

(** @canonical Cohttp.Accept_types *)
module Accept_types = Cohttp__Accept_types

(** @canonical Cohttp.Auth *)
module Auth = Cohttp__Auth

(** @canonical Cohttp.Body *)
module Body = Cohttp__Body

(** @canonical Cohttp.Client *)
module Client = Cohttp__Client

(** @canonical Cohttp.Code *)
module Code = Cohttp__Code

(** @canonical Cohttp.Conf *)
module Conf = Cohttp__Conf

(** @canonical Cohttp.Connection *)
module Connection = Cohttp__Connection

(** @canonical Cohttp.Cookie *)
module Cookie = Cohttp__Cookie

(** @canonical Cohttp.Header *)
module Header = Cohttp__Header

(** @canonical Cohttp.Header_io *)
module Header_io = Cohttp__Header_io

(** @canonical Cohttp.Link *)
module Link = Cohttp__Link

(** @canonical Cohttp.Path *)
module Path = Cohttp__Path

(** @canonical Cohttp.Request *)
module Request = Cohttp__Request

(** @canonical Cohttp.Response *)
module Response = Cohttp__Response

(** @canonical Cohttp.S *)
module S = Cohttp__S

(** @canonical Cohttp.Server *)
module Server = Cohttp__Server

(** @canonical Cohttp.String_io *)
module String_io = Cohttp__String_io

(** @canonical Cohttp.Transfer *)
module Transfer = Cohttp__Transfer

(** @canonical Cohttp.Transfer_io *)
module Transfer_io = Cohttp__Transfer_io
