(* generated by dune *)

(** @canonical Eio.Buf_read *)
module Buf_read = Eio__Buf_read

(** @canonical Eio.Buf_write *)
module Buf_write = Eio__Buf_write

(** @canonical Eio.Condition *)
module Condition = Eio__Condition

(** @canonical Eio.Domain_manager *)
module Domain_manager = Eio__Domain_manager

(** @canonical Eio.Eio_mutex *)
module Eio_mutex = Eio__Eio_mutex

(** @canonical Eio.Executor_pool *)
module Executor_pool = Eio__Executor_pool

(** @canonical Eio.File *)
module File = Eio__File

(** @canonical Eio.Flow *)
module Flow = Eio__Flow

(** @canonical Eio.Fs *)
module Fs = Eio__Fs

(** @canonical Eio.Hook *)
module Hook = Eio__Hook

(** @canonical Eio.Lazy *)
module Lazy = Eio__Lazy

(** @canonical Eio.Net *)
module Net = Eio__Net

(** @canonical Eio.Path *)
module Path = Eio__Path

(** @canonical Eio.Pool *)
module Pool = Eio__Pool

(** @canonical Eio.Process *)
module Process = Eio__Process

(** @canonical Eio.Resource *)
module Resource = Eio__Resource

(** @canonical Eio.Sem_state *)
module Sem_state = Eio__Sem_state

(** @canonical Eio.Semaphore *)
module Semaphore = Eio__Semaphore

(** @canonical Eio.Std *)
module Std = Eio__Std

(** @canonical Eio.Stream *)
module Stream = Eio__Stream

(** @canonical Eio.Sync *)
module Sync = Eio__Sync

(** @canonical Eio.Time *)
module Time = Eio__Time

(** @canonical Eio.Waiters *)
module Waiters = Eio__Waiters

module Eio__ = struct end
[@@deprecated "this module is shadowed"]
