(* generated by dune *)

(** @canonical Eio_main.Linux_backend *)
module Linux_backend = Eio_main__Linux_backend

(** @canonical Eio_main.Posix_backend *)
module Posix_backend = Eio_main__Posix_backend

(** @canonical Eio_main.Windows_backend *)
module Windows_backend = Eio_main__Windows_backend

module Eio_main__ = struct end
[@@deprecated "this module is shadowed"]
