(* generated by dune *)

(** @canonical Bin_prot.Binable *)
module Binable = Bin_prot__Binable

(** @canonical Bin_prot.Blob *)
module Blob = Bin_prot__Blob

(** @canonical Bin_prot.Common *)
module Common = Bin_prot__Common

(** @canonical Bin_prot.Md5 *)
module Md5 = Bin_prot__Md5

(** @canonical Bin_prot.Nat0 *)
module Nat0 = Bin_prot__Nat0

(** @canonical Bin_prot.Read *)
module Read = Bin_prot__Read

(** @canonical Bin_prot.Shape *)
module Shape = Bin_prot__Shape

(** @canonical Bin_prot.Size *)
module Size = Bin_prot__Size

(** @canonical Bin_prot.Std *)
module Std = Bin_prot__Std

(** @canonical Bin_prot.Type_class *)
module Type_class = Bin_prot__Type_class

(** @canonical Bin_prot.Utils *)
module Utils = Bin_prot__Utils

(** @canonical Bin_prot.Utils_intf *)
module Utils_intf = Bin_prot__Utils_intf

(** @canonical Bin_prot.Write *)
module Write = Bin_prot__Write
