name: "Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-shell --command "dune runtest --profile=dev cohttp cohttp-async cohttp-curl cohttp-curl-async cohttp-curl-lwt cohttp-lwt cohttp-lwt-unix cohttp-mirage cohttp-server-lwt-unix cohttp-top http"
        nix-shell --command "dune build --profile=dev cohttp-lwt-jsoo"
