(* generated by dune *)

(** @canonical Expect_test_matcher.Choose_tag *)
module Choose_tag = Expect_test_matcher__Choose_tag

(** @canonical Expect_test_matcher.Cst *)
module Cst = Expect_test_matcher__Cst

(** @canonical Expect_test_matcher.Fmt *)
module Fmt = Expect_test_matcher__Fmt

(** @canonical Expect_test_matcher.Import *)
module Import = Expect_test_matcher__Import

(** @canonical Expect_test_matcher.Lexer *)
module Lexer = Expect_test_matcher__Lexer

(** @canonical Expect_test_matcher.Matcher *)
module Matcher = Expect_test_matcher__Matcher

(** @canonical Expect_test_matcher.Reconcile *)
module Reconcile = Expect_test_matcher__Reconcile
