(* generated by dune *)

(** @canonical Eio_utils.Lf_queue *)
module Lf_queue = Eio_utils__Lf_queue

(** @canonical Eio_utils.Suspended *)
module Suspended = Eio_utils__Suspended

(** @canonical Eio_utils.Zzz *)
module Zzz = Eio_utils__Zzz

module Eio_utils__ = struct end
[@@deprecated "this module is shadowed"]
