language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PINS="optint.dev:."
  matrix:
  - PACKAGE="optint" OCAML_VERSION=4.08 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.09 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.10 TESTS=true
  - PACKAGE="optint" OCAML_VERSION=4.11 TESTS=true
