#ifndef CONFIG_H_CONFIG_H
#define CONFIG_H_CONFIG_H
#undef  JSC_ARCH_BIG_ENDIAN
#define JSC_ARCH_SIXTYFOUR
#define JSC_CLOCK_GETCPUCLOCKID
#define JSC_EVENTFD
#define JSC_FDATASYNC
#define JSC_LINUX_EXT
#define JSC_MKOSTEMP
#define JSC_MSG_NOSIGNAL
#define JSC_POSIX_TIMERS
#define JSC_PTHREAD_NP
#define JSC_READDIR_DTYPE
#define JSC_RECVMMSG
#define JSC_RLIMIT_AS
#define JSC_RLIMIT_NICE
#undef  JSC_SO_NOSIGPIPE
#define JSC_THREAD_CPUTIME
#define JSC_THREAD_ID_METHOD (1)
#define JSC_TIMERFD
#define JSC_TIMESPEC
#define JSC_WORDEXP
#endif
