(* generated by dune *)

(** @canonical Core.Arg *)
module Arg = Core__Arg

(** @canonical Core.Array *)
module Array = Core__Array

(** @canonical Core.Bag *)
module Bag = Core__Bag

(** @canonical Core.Bag_intf *)
module Bag_intf = Core__Bag_intf

(** @canonical Core.Bigbuffer *)
module Bigbuffer = Core__Bigbuffer

(** @canonical Core.Bigbuffer_internal *)
module Bigbuffer_internal = Core__Bigbuffer_internal

(** @canonical Core.Bigstring *)
module Bigstring = Core__Bigstring

(** @canonical Core.Bigsubstring *)
module Bigsubstring = Core__Bigsubstring

(** @canonical Core.Binable *)
module Binable = Core__Binable

(** @canonical Core.Binable0 *)
module Binable0 = Core__Binable0

(** @canonical Core.Binable_intf *)
module Binable_intf = Core__Binable_intf

(** @canonical Core.Binary_searchable *)
module Binary_searchable = Core__Binary_searchable

(** @canonical Core.Binary_searchable_intf *)
module Binary_searchable_intf = Core__Binary_searchable_intf

(** @canonical Core.Blang *)
module Blang = Core__Blang

(** @canonical Core.Blit *)
module Blit = Core__Blit

(** @canonical Core.Blit_intf *)
module Blit_intf = Core__Blit_intf

(** @canonical Core.Bool *)
module Bool = Core__Bool

(** @canonical Core.Bounded_index *)
module Bounded_index = Core__Bounded_index

(** @canonical Core.Bounded_index_intf *)
module Bounded_index_intf = Core__Bounded_index_intf

(** @canonical Core.Byte_units *)
module Byte_units = Core__Byte_units

(** @canonical Core.Byte_units0 *)
module Byte_units0 = Core__Byte_units0

(** @canonical Core.Bytes *)
module Bytes = Core__Bytes

(** @canonical Core.Char *)
module Char = Core__Char

(** @canonical Core.Command_internal *)
module Command_internal = Core__Command_internal

(** @canonical Core.Command_shape *)
module Command_shape = Core__Command_shape

(** @canonical Core.Comparable *)
module Comparable = Core__Comparable

(** @canonical Core.Comparable_intf *)
module Comparable_intf = Core__Comparable_intf

(** @canonical Core.Comparator *)
module Comparator = Core__Comparator

(** @canonical Core.Container *)
module Container = Core__Container

(** @canonical Core.Container_intf *)
module Container_intf = Core__Container_intf

(** @canonical Core.Core_bin_prot *)
module Core_bin_prot = Core__Core_bin_prot

(** @canonical Core.Core_pervasives *)
module Core_pervasives = Core__Core_pervasives

(** @canonical Core.Core_sys *)
module Core_sys = Core__Core_sys

(** @canonical Core.Date *)
module Date = Core__Date

(** @canonical Core.Date0 *)
module Date0 = Core__Date0

(** @canonical Core.Date0_intf *)
module Date0_intf = Core__Date0_intf

(** @canonical Core.Date_intf *)
module Date_intf = Core__Date_intf

(** @canonical Core.Day_of_week *)
module Day_of_week = Core__Day_of_week

(** @canonical Core.Day_of_week_intf *)
module Day_of_week_intf = Core__Day_of_week_intf

(** @canonical Core.Debug *)
module Debug = Core__Debug

(** @canonical Core.Deprecate_pipe_bang *)
module Deprecate_pipe_bang = Core__Deprecate_pipe_bang

(** @canonical Core.Deque *)
module Deque = Core__Deque

(** @canonical Core.Deriving_hash *)
module Deriving_hash = Core__Deriving_hash

(** @canonical Core.Deriving_hash_intf *)
module Deriving_hash_intf = Core__Deriving_hash_intf

(** @canonical Core.Digit_string_helpers *)
module Digit_string_helpers = Core__Digit_string_helpers

(** @canonical Core.Doubly_linked *)
module Doubly_linked = Core__Doubly_linked

(** @canonical Core.Doubly_linked_intf *)
module Doubly_linked_intf = Core__Doubly_linked_intf

(** @canonical Core.Either *)
module Either = Core__Either

(** @canonical Core.Error *)
module Error = Core__Error

(** @canonical Core.Fdeque *)
module Fdeque = Core__Fdeque

(** @canonical Core.Filename *)
module Filename = Core__Filename

(** @canonical Core.Float *)
module Float = Core__Float

(** @canonical Core.Float_with_finite_only_serialization *)
module Float_with_finite_only_serialization = Core__Float_with_finite_only_serialization

(** @canonical Core.Fn *)
module Fn = Core__Fn

(** @canonical Core.Fqueue *)
module Fqueue = Core__Fqueue

(** @canonical Core.Gc *)
module Gc = Core__Gc

(** @canonical Core.Hash_queue *)
module Hash_queue = Core__Hash_queue

(** @canonical Core.Hash_queue_intf *)
module Hash_queue_intf = Core__Hash_queue_intf

(** @canonical Core.Hash_set *)
module Hash_set = Core__Hash_set

(** @canonical Core.Hash_set_intf *)
module Hash_set_intf = Core__Hash_set_intf

(** @canonical Core.Hashable *)
module Hashable = Core__Hashable

(** @canonical Core.Hashable_intf *)
module Hashable_intf = Core__Hashable_intf

(** @canonical Core.Hashtbl *)
module Hashtbl = Core__Hashtbl

(** @canonical Core.Hashtbl_intf *)
module Hashtbl_intf = Core__Hashtbl_intf

(** @canonical Core.Hexdump *)
module Hexdump = Core__Hexdump

(** @canonical Core.Hexdump_intf *)
module Hexdump_intf = Core__Hexdump_intf

(** @canonical Core.Host_and_port *)
module Host_and_port = Core__Host_and_port

(** @canonical Core.Identifiable *)
module Identifiable = Core__Identifiable

(** @canonical Core.Identifiable_intf *)
module Identifiable_intf = Core__Identifiable_intf

(** @canonical Core.Immediate_option *)
module Immediate_option = Core__Immediate_option

(** @canonical Core.Immediate_option_intf *)
module Immediate_option_intf = Core__Immediate_option_intf

(** @canonical Core.Import *)
module Import = Core__Import

(** @canonical Core.Indexed_container *)
module Indexed_container = Core__Indexed_container

(** @canonical Core.Indexed_container_intf *)
module Indexed_container_intf = Core__Indexed_container_intf

(** @canonical Core.Info *)
module Info = Core__Info

(** @canonical Core.Info_intf *)
module Info_intf = Core__Info_intf

(** @canonical Core.Int *)
module Int = Core__Int

(** @canonical Core.Int32 *)
module Int32 = Core__Int32

(** @canonical Core.Int63 *)
module Int63 = Core__Int63

(** @canonical Core.Int64 *)
module Int64 = Core__Int64

(** @canonical Core.Int_intf *)
module Int_intf = Core__Int_intf

(** @canonical Core.Interfaces *)
module Interfaces = Core__Interfaces

(** @canonical Core.Lazy *)
module Lazy = Core__Lazy

(** @canonical Core.Linked_queue *)
module Linked_queue = Core__Linked_queue

(** @canonical Core.List *)
module List = Core__List

(** @canonical Core.List0 *)
module List0 = Core__List0

(** @canonical Core.Make_stable *)
module Make_stable = Core__Make_stable

(** @canonical Core.Make_substring *)
module Make_substring = Core__Make_substring

(** @canonical Core.Make_substring_intf *)
module Make_substring_intf = Core__Make_substring_intf

(** @canonical Core.Map *)
module Map = Core__Map

(** @canonical Core.Map_intf *)
module Map_intf = Core__Map_intf

(** @canonical Core.Maybe_bound *)
module Maybe_bound = Core__Maybe_bound

(** @canonical Core.Md5 *)
module Md5 = Core__Md5

(** @canonical Core.Memo *)
module Memo = Core__Memo

(** @canonical Core.Month *)
module Month = Core__Month

(** @canonical Core.Month_intf *)
module Month_intf = Core__Month_intf

(** @canonical Core.Nativeint *)
module Nativeint = Core__Nativeint

(** @canonical Core.Never_returns *)
module Never_returns = Core__Never_returns

(** @canonical Core.No_polymorphic_compare *)
module No_polymorphic_compare = Core__No_polymorphic_compare

(** @canonical Core.Nothing *)
module Nothing = Core__Nothing

(** @canonical Core.Ofday_float *)
module Ofday_float = Core__Ofday_float

(** @canonical Core.Ofday_helpers *)
module Ofday_helpers = Core__Ofday_helpers

(** @canonical Core.Ofday_intf *)
module Ofday_intf = Core__Ofday_intf

(** @canonical Core.Ofday_ns *)
module Ofday_ns = Core__Ofday_ns

(** @canonical Core.Only_in_test *)
module Only_in_test = Core__Only_in_test

(** @canonical Core.Option *)
module Option = Core__Option

(** @canonical Core.Option_array *)
module Option_array = Core__Option_array

(** @canonical Core.Optional_syntax *)
module Optional_syntax = Core__Optional_syntax

(** @canonical Core.Optional_syntax_intf *)
module Optional_syntax_intf = Core__Optional_syntax_intf

(** @canonical Core.Or_error *)
module Or_error = Core__Or_error

(** @canonical Core.Ordered_collection_common *)
module Ordered_collection_common = Core__Ordered_collection_common

(** @canonical Core.Ordering *)
module Ordering = Core__Ordering

(** @canonical Core.Percent *)
module Percent = Core__Percent

(** @canonical Core.Perms *)
module Perms = Core__Perms

(** @canonical Core.Pid *)
module Pid = Core__Pid

(** @canonical Core.Printexc *)
module Printexc = Core__Printexc

(** @canonical Core.Printf *)
module Printf = Core__Printf

(** @canonical Core.Queue *)
module Queue = Core__Queue

(** @canonical Core.Queue_intf *)
module Queue_intf = Core__Queue_intf

(** @canonical Core.Quickcheck *)
module Quickcheck = Core__Quickcheck

(** @canonical Core.Quickcheck_intf *)
module Quickcheck_intf = Core__Quickcheck_intf

(** @canonical Core.Quickcheckable *)
module Quickcheckable = Core__Quickcheckable

(** @canonical Core.Quickcheckable_intf *)
module Quickcheckable_intf = Core__Quickcheckable_intf

(** @canonical Core.Ref *)
module Ref = Core__Ref

(** @canonical Core.Result *)
module Result = Core__Result

(** @canonical Core.Robustly_comparable *)
module Robustly_comparable = Core__Robustly_comparable

(** @canonical Core.Sequence *)
module Sequence = Core__Sequence

(** @canonical Core.Set *)
module Set = Core__Set

(** @canonical Core.Set_intf *)
module Set_intf = Core__Set_intf

(** @canonical Core.Set_once *)
module Set_once = Core__Set_once

(** @canonical Core.Sexp *)
module Sexp = Core__Sexp

(** @canonical Core.Sexpable *)
module Sexpable = Core__Sexpable

(** @canonical Core.Sign *)
module Sign = Core__Sign

(** @canonical Core.Sign_or_nan *)
module Sign_or_nan = Core__Sign_or_nan

(** @canonical Core.Signal *)
module Signal = Core__Signal

(** @canonical Core.Source_code_position *)
module Source_code_position = Core__Source_code_position

(** @canonical Core.Source_code_position0 *)
module Source_code_position0 = Core__Source_code_position0

(** @canonical Core.Span_float *)
module Span_float = Core__Span_float

(** @canonical Core.Span_helpers *)
module Span_helpers = Core__Span_helpers

(** @canonical Core.Span_intf *)
module Span_intf = Core__Span_intf

(** @canonical Core.Span_ns *)
module Span_ns = Core__Span_ns

(** @canonical Core.Stable *)
module Stable = Core__Stable

(** @canonical Core.Stable_comparable *)
module Stable_comparable = Core__Stable_comparable

(** @canonical Core.Stable_int63able *)
module Stable_int63able = Core__Stable_int63able

(** @canonical Core.Stable_internal *)
module Stable_internal = Core__Stable_internal

(** @canonical Core.Stable_module_types *)
module Stable_module_types = Core__Stable_module_types

(** @canonical Core.Stable_unit_test *)
module Stable_unit_test = Core__Stable_unit_test

(** @canonical Core.Stable_unit_test_intf *)
module Stable_unit_test_intf = Core__Stable_unit_test_intf

(** @canonical Core.Stack *)
module Stack = Core__Stack

(** @canonical Core.Std_internal *)
module Std_internal = Core__Std_internal

(** @canonical Core.String *)
module String = Core__String

(** @canonical Core.String_id *)
module String_id = Core__String_id

(** @canonical Core.String_id_intf *)
module String_id_intf = Core__String_id_intf

(** @canonical Core.Substring *)
module Substring = Core__Substring

(** @canonical Core.Substring_intf *)
module Substring_intf = Core__Substring_intf

(** @canonical Core.T *)
module T = Core__T

(** @canonical Core.Time *)
module Time = Core__Time

(** @canonical Core.Time0_intf *)
module Time0_intf = Core__Time0_intf

(** @canonical Core.Time_float *)
module Time_float = Core__Time_float

(** @canonical Core.Time_float0 *)
module Time_float0 = Core__Time_float0

(** @canonical Core.Time_intf *)
module Time_intf = Core__Time_intf

(** @canonical Core.Time_ns *)
module Time_ns = Core__Time_ns

(** @canonical Core.Time_ns_alternate_sexp *)
module Time_ns_alternate_sexp = Core__Time_ns_alternate_sexp

(** @canonical Core.Time_ns_intf *)
module Time_ns_intf = Core__Time_ns_intf

(** @canonical Core.Tuple *)
module Tuple = Core__Tuple

(** @canonical Core.Type_equal *)
module Type_equal = Core__Type_equal

(** @canonical Core.Type_equal_intf *)
module Type_equal_intf = Core__Type_equal_intf

(** @canonical Core.Type_immediacy *)
module Type_immediacy = Core__Type_immediacy

(** @canonical Core.Uniform_array *)
module Uniform_array = Core__Uniform_array

(** @canonical Core.Union_find *)
module Union_find = Core__Union_find

(** @canonical Core.Unique_id *)
module Unique_id = Core__Unique_id

(** @canonical Core.Unique_id_intf *)
module Unique_id_intf = Core__Unique_id_intf

(** @canonical Core.Unit *)
module Unit = Core__Unit

(** @canonical Core.Unit_of_time *)
module Unit_of_time = Core__Unit_of_time

(** @canonical Core.Validated *)
module Validated = Core__Validated

(** @canonical Core.Validated_intf *)
module Validated_intf = Core__Validated_intf

(** @canonical Core.Zone *)
module Zone = Core__Zone

(** @canonical Core.Zone_intf *)
module Zone_intf = Core__Zone_intf
