(* generated by dune *)

(** @canonical Eio_mock.Action *)
module Action = Eio_mock__Action

(** @canonical Eio_mock.Backend *)
module Backend = Eio_mock__Backend

(** @canonical Eio_mock.Clock *)
module Clock = Eio_mock__Clock

(** @canonical Eio_mock.Domain_manager *)
module Domain_manager = Eio_mock__Domain_manager

(** @canonical Eio_mock.Flow *)
module Flow = Eio_mock__Flow

(** @canonical Eio_mock.Handler *)
module Handler = Eio_mock__Handler

(** @canonical Eio_mock.Net *)
module Net = Eio_mock__Net

module Eio_mock__ = struct end
[@@deprecated "this module is shadowed"]
