volumes:
  _build:
  _boot:
services:
  dune:
    image: dune
    user: opam
    tty: true
    privileged: true
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    environment:
      HISTFILE: /home/opam/dune/.git/.bash_history
    volumes:
      - ../:/home/opam/dune
      - _build:/home/opam/dune/_build/
      - _boot:/home/opam/dune/_boot/
