(* generated by dune *)

(** @canonical Eio_linux.Err *)
module Err = Eio_linux__Err

(** @canonical Eio_linux.Low_level *)
module Low_level = Eio_linux__Low_level

(** @canonical Eio_linux.Sched *)
module Sched = Eio_linux__Sched

module Eio_linux__ = struct end
[@@deprecated "this module is shadowed"]
