(* generated by dune *)

(** @canonical Ppx_quickcheck_expander.Clause_syntax *)
module Clause_syntax = Ppx_quickcheck_expander__Clause_syntax

(** @canonical Ppx_quickcheck_expander.Clause_syntax_intf *)
module Clause_syntax_intf = Ppx_quickcheck_expander__Clause_syntax_intf

(** @canonical Ppx_quickcheck_expander.Environment *)
module Environment = Ppx_quickcheck_expander__Environment

(** @canonical Ppx_quickcheck_expander.Field_syntax *)
module Field_syntax = Ppx_quickcheck_expander__Field_syntax

(** @canonical Ppx_quickcheck_expander.Field_syntax_intf *)
module Field_syntax_intf = Ppx_quickcheck_expander__Field_syntax_intf

(** @canonical Ppx_quickcheck_expander.Import *)
module Import = Ppx_quickcheck_expander__Import

(** @canonical Ppx_quickcheck_expander.Ppx_generator_expander *)
module Ppx_generator_expander = Ppx_quickcheck_expander__Ppx_generator_expander

(** @canonical Ppx_quickcheck_expander.Ppx_observer_expander *)
module Ppx_observer_expander = Ppx_quickcheck_expander__Ppx_observer_expander

(** @canonical Ppx_quickcheck_expander.Ppx_shrinker_expander *)
module Ppx_shrinker_expander = Ppx_quickcheck_expander__Ppx_shrinker_expander
