(* generated by dune *)

(** @canonical Eio__core.Broadcast *)
module Broadcast = Eio__core__Broadcast

(** @canonical Eio__core.Cancel *)
module Cancel = Eio__core__Cancel

(** @canonical Eio__core.Cells *)
module Cells = Eio__core__Cells

(** @canonical Eio__core.Debug *)
module Debug = Eio__core__Debug

(** @canonical Eio__core.Dla *)
module Dla = Eio__core__Dla

(** @canonical Eio__core.Exn *)
module Exn = Eio__core__Exn

(** @canonical Eio__core.Fiber *)
module Fiber = Eio__core__Fiber

(** @canonical Eio__core.Promise *)
module Promise = Eio__core__Promise

(** @canonical Eio__core.Single_waiter *)
module Single_waiter = Eio__core__Single_waiter

(** @canonical Eio__core.Suspend *)
module Suspend = Eio__core__Suspend

(** @canonical Eio__core.Switch *)
module Switch = Eio__core__Switch

(** @canonical Eio__core.Trace *)
module Trace = Eio__core__Trace

module Eio__core__ = struct end
[@@deprecated "this module is shadowed"]
