(* generated by dune *)

(** @canonical Parsexp.Automaton *)
module Automaton = Parsexp__Automaton

(** @canonical Parsexp.Automaton_action *)
module Automaton_action = Parsexp__Automaton_action

(** @canonical Parsexp.Automaton_intf *)
module Automaton_intf = Parsexp__Automaton_intf

(** @canonical Parsexp.Automaton_stack *)
module Automaton_stack = Parsexp__Automaton_stack

(** @canonical Parsexp.Automaton_stack_intf *)
module Automaton_stack_intf = Parsexp__Automaton_stack_intf

(** @canonical Parsexp.Automaton_state *)
module Automaton_state = Parsexp__Automaton_state

(** @canonical Parsexp.Automaton_state_intf *)
module Automaton_state_intf = Parsexp__Automaton_state_intf

(** @canonical Parsexp.Automaton_tables *)
module Automaton_tables = Parsexp__Automaton_tables

(** @canonical Parsexp.Conv *)
module Conv = Parsexp__Conv

(** @canonical Parsexp.Conv_error *)
module Conv_error = Parsexp__Conv_error

(** @canonical Parsexp.Conv_intf *)
module Conv_intf = Parsexp__Conv_intf

(** @canonical Parsexp.Cst *)
module Cst = Parsexp__Cst

(** @canonical Parsexp.Import *)
module Import = Parsexp__Import

(** @canonical Parsexp.Of_sexp_error *)
module Of_sexp_error = Parsexp__Of_sexp_error

(** @canonical Parsexp.Old_parser_cont_state *)
module Old_parser_cont_state = Parsexp__Old_parser_cont_state

(** @canonical Parsexp.Parse_error *)
module Parse_error = Parsexp__Parse_error

(** @canonical Parsexp.Parse_error_intf *)
module Parse_error_intf = Parsexp__Parse_error_intf

(** @canonical Parsexp.Parser *)
module Parser = Parsexp__Parser

(** @canonical Parsexp.Parser_intf *)
module Parser_intf = Parsexp__Parser_intf

(** @canonical Parsexp.Parsexp_intf *)
module Parsexp_intf = Parsexp__Parsexp_intf

(** @canonical Parsexp.Positions *)
module Positions = Parsexp__Positions
