name: Run starred_ml

on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * 0

permissions:
  pull-requests: write
  contents: write

jobs:
  starred_ml:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3.0.9
        with:
          ocaml-compiler: "5.2.1"

      - run: opam install starred_ml

      - name: Generate awesome README
        env:
          TOKEN: ${{ secrets.TOKEN }} # This token is a PAT with starred read access
        run: opam exec -- starred_ml > README.md
        working-directory: ${{ github.event.repository.name }}

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: ${{ github.event.repository.updated_at}} starred_ml update
          title: ${{ github.run_number }} starred_ml update
          branch-suffix: short-commit-hash
          path: ${{ github.event.repository.name }}
