on:
  workflow_dispatch:
  schedule:
  - cron: 30 0 * * 0

permissions:
  pull-requests: write
  contents: write

jobs:
  starred_ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
  
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.1'

      - run: opam install starred_ml

      - name: Generate awesome README
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: opam exec -- starred_ml > README.md
        working-directory: ${{ github.event.repository.name }}
  
  
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ github.event.repository.updated_at}} starred_ml update
          title: ${{ github.run_number }} starred_ml update
          branch-suffix: short-commit-hash
          path: ${{ github.event.repository.name }}
